server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-db}:${DB_PORT:3306}/rechargenova?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: 86400000

admin:
  credentials:
    email: ${ADMIN_EMAIL:admin@gmail.com}
    password: ${ADMIN_PASSWORD:admin123}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dnakxnjo2}
  api-key: ${CLOUDINARY_API_KEY:174754673251635}
  api-secret: ${CLOUDINARY_API_SECRET:XoeBVFOuBxiIVPrGNrb_B5QhPww}

springdoc:
  api-docs:
    path: ${SWAGGER_USER_URL:/users/v3/api-docs}