server:
  port: 8090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**