server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:oracle:thin:@//host.docker.internal:1521/xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: scott
    password: tiger

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

# ✅ Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

# 🔐 JWT Configuration
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

# 🔗 Feign Client Config (IMPORTANT for microservices)
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# 🔥 Distributed Tracing (Spring Boot 3 + Zipkin)
management:
  tracing:
    sampling:
      probability: 1.0   # capture all requests

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

cloudinary:
  cloud-name: ${AUTH_SERVICE_CLOUDINARY_CLOUD_NAME:dnakxnjo2}
  api-key: ${AUTH_SERVICE_CLOUDINARY_API_KEY:174754673251635}
  api-secret: ${AUTH_SERVICE_CLOUDINARY_API_SECRET:XoeBVFOuBxiIVPrGNrb_B5QhPww}