server:
  port: 8085
  forward-headers-strategy: framework

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-db}:${DB_PORT:3306}/rechargenova?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:sanjanachandel82@gmail.com}
    password: ${MAIL_PASSWORD:fpwqqzorvujavysz}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  api-docs:
    path: ${SWAGGER_NOTIFICATION_URL:/api/notifications/v3/api-docs}